/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import funciones_varias.Img_fondo_label;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author wwwki
 */
public class jfFinanzas extends javax.swing.JFrame {

    /**
     * Creates new form jfMenu
     */
    public jfFinanzas() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //FONDO CON IMAGEN--------------------------------------------------------------------------------
        Img_fondo_label fondoLabel = new Img_fondo_label();
        fondoLabel.Llenar_Label("ventana_reportes.jpg", lblFondo);
        
        jpFechas.setBackground(new Color(0,0,0,64));
        jpFac.setBackground(new Color(0,0,0,64));
        jpCliente.setBackground(new Color(0,0,0,64));
        jpForma.setBackground(new Color(0,0,0,64));
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferio);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferio1);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferio2);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferio3);
        
        //Color myColor = new Color(255,255,208);
        jtFienanza.setBackground(Color.BLACK);
        
//        JScrollPane scroll = new JScrollPane(jtFienanza);
////        jtFienanza.setFillsViewportHeight(true);
//        scroll.getViewport().setBackground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalir = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFienanza = new javax.swing.JTable();
        jpForma = new javax.swing.JPanel();
        jchkForma = new javax.swing.JRadioButton();
        lblLineaInferio3 = new javax.swing.JLabel();
        jpCliente = new javax.swing.JPanel();
        jrFechas = new javax.swing.JRadioButton();
        lblLineaInferio2 = new javax.swing.JLabel();
        jpFechas = new javax.swing.JPanel();
        jrFechas1 = new javax.swing.JRadioButton();
        lblLineaInferio = new javax.swing.JLabel();
        jpFac = new javax.swing.JPanel();
        jrNoFac1 = new javax.swing.JRadioButton();
        lblLineaInferio1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn on_32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 40));

        lblNombreCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNombreCliente.setForeground(java.awt.Color.white);
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setText("Finanzas");
        getContentPane().add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 700, -1));

        jScrollPane1.setForeground(java.awt.Color.black);

        jtFienanza.setBackground(java.awt.Color.black);
        jtFienanza.setForeground(java.awt.Color.black);
        jtFienanza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtFienanza.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jtFienanza.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtFienanza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFienanzaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFienanza);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 700, 250));

        jpForma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jpForma.setOpaque(false);
        jpForma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jchkForma.setBackground(new java.awt.Color(41, 42, 44));
        jchkForma.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jchkForma.setForeground(new java.awt.Color(255, 255, 255));
        jchkForma.setText("Forma de Pago:");
        jchkForma.setOpaque(false);
        jchkForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFormaActionPerformed(evt);
            }
        });
        jpForma.add(jchkForma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 160, 20));
        jpForma.add(lblLineaInferio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 7));

        getContentPane().add(jpForma, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 340, 60));

        jpCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jpCliente.setOpaque(false);
        jpCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrFechas.setBackground(new java.awt.Color(41, 42, 44));
        jrFechas.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jrFechas.setForeground(new java.awt.Color(255, 255, 255));
        jrFechas.setText("Cliente:");
        jrFechas.setOpaque(false);
        jrFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFechasActionPerformed(evt);
            }
        });
        jpCliente.add(jrFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 280, 20));
        jpCliente.add(lblLineaInferio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 7));

        getContentPane().add(jpCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 330, 60));

        jpFechas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jpFechas.setOpaque(false);
        jpFechas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrFechas1.setBackground(new java.awt.Color(41, 42, 44));
        jrFechas1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jrFechas1.setForeground(new java.awt.Color(255, 255, 255));
        jrFechas1.setText("Fecha Desde:         Fecha Hasta:");
        jrFechas1.setOpaque(false);
        jrFechas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFechas1ActionPerformed(evt);
            }
        });
        jpFechas.add(jrFechas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 280, 20));
        jpFechas.add(lblLineaInferio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 7));

        getContentPane().add(jpFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 330, 60));

        jpFac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jpFac.setOpaque(false);
        jpFac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrNoFac1.setBackground(new java.awt.Color(41, 42, 44));
        jrNoFac1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jrNoFac1.setForeground(new java.awt.Color(255, 255, 255));
        jrNoFac1.setText("Por No. de Factura:");
        jrNoFac1.setOpaque(false);
        jrNoFac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNoFac1ActionPerformed(evt);
            }
        });
        jpFac.add(jrNoFac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 160, 20));
        jpFac.add(lblLineaInferio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 7));

        getContentPane().add(jpFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 340, 60));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buscar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 400, 40));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE); 
        jfMenu menu = new jfMenu();
        menu.setVisible(true);
//        int dialog = JOptionPane.YES_NO_OPTION;
//        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
//        if(result == 0){
//            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);            
//        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void jchkFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkFormaActionPerformed

    private void jrNoFac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNoFac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrNoFac1ActionPerformed

    private void jrFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrFechasActionPerformed

    private void jrFechas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFechas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrFechas1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);   
        jfPagar pc = new jfPagar();     
          pc.setVisible(true);            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtFienanzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFienanzaMouseClicked
        
        try {
            if(evt.getClickCount()==2){
            
//                   if (this.jtableCuentas.getRowCount() == 0 )
//                        { 
//                            JOptionPane.showMessageDialog(null,"No hay registros para leccionar","CyCo",JOptionPane.INFORMATION_MESSAGE); 
//                            return;
//                        }
//                   varias_funciones vr = new varias_funciones();
                   jfPagar pc = new jfPagar();
//                   String sId_fac = String.valueOf(jtableCuentas.getValueAt(jtableCuentas.getSelectedRow(),0));
//                   pc.id_factura = Integer.parseInt(sId_fac);                                      
//                   pc.lblSerie.setText(String.valueOf(jtableCuentas.getValueAt(jtableCuentas.getSelectedRow(),2)));
//                   pc.lblNo.setText(String.valueOf(jtableCuentas.getValueAt(jtableCuentas.getSelectedRow(),3)));
//                   pc.lblFecha.setText(vr.MostrarformatoFecha(String.valueOf(jtableCuentas.getValueAt(jtableCuentas.getSelectedRow(),1))));
//                   pc.lblTotal.setText(String.valueOf(jtableCuentas.getValueAt(jtableCuentas.getSelectedRow(),5)));
//                   pc.calculo_pagar();
//                   this.dispose();
                   pc.setVisible(true);                                                                                               
        }
                                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error en: " +e, "CyCo", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        
        
        
    }//GEN-LAST:event_jtFienanzaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfFinanzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfFinanzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfFinanzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfFinanzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfFinanzas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jchkForma;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpFac;
    private javax.swing.JPanel jpFechas;
    private javax.swing.JPanel jpForma;
    private javax.swing.JRadioButton jrFechas;
    private javax.swing.JRadioButton jrFechas1;
    private javax.swing.JRadioButton jrNoFac1;
    private javax.swing.JTable jtFienanza;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLineaInferio;
    private javax.swing.JLabel lblLineaInferio1;
    private javax.swing.JLabel lblLineaInferio2;
    private javax.swing.JLabel lblLineaInferio3;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
