/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import funciones_varias.Img_fondo_label;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwki
 */
public class jfGarantias extends javax.swing.JFrame {

    /**
     * Creates new form jfMenu
     */
    public jfGarantias() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //FONDO CON IMAGEN--------------------------------------------------------------------------------              
        Img_fondo_label fondoLabel = new Img_fondo_label();
        fondoLabel.Llenar_Label("garantias.jpg", lblFondo);
        fondoLabel.Llenar_Label("garantias.png", lblTitulo);    
        fondoLabel.Llenar_Label("barra_titulo.png", lblBarraTitulo);
        
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior1);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior2);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior3);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior4);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior5);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior6);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior7);
        fondoLabel.Llenar_Label("barra_una_punta.png", lblLineaInferior8);
        
                        
        
        jtxtImei.setBackground(new Color(0,0,0,64));
        jtxtFechaR.setBackground(new Color(0,0,0,64));
        jtxtCatego.setBackground(new Color(0,0,0,64));        
        jtxtMarca.setBackground(new Color(0,0,0,64));
        jtxtModelo.setBackground(new Color(0,0,0,64));
        jtxtCompra.setBackground(new Color(0,0,0,64));
        jtxtCliente.setBackground(new Color(0,0,0,64));
        jtxtCedula.setBackground(new Color(0,0,0,64));
        jtxtTele.setBackground(new Color(0,0,0,64));        
        
        jAreaFalla.setLineWrap(true);
        jAreaFalla.setWrapStyleWord(true);                  
        jAreaInfo.setLineWrap(true);
        jAreaInfo.setWrapStyleWord(true);  
        
        



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalir = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        jtxtCatego = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblHora2 = new javax.swing.JLabel();
        jtxtImei = new javax.swing.JTextField();
        jtxtMarca = new javax.swing.JTextField();
        jtxtModelo = new javax.swing.JTextField();
        jtxtCompra = new javax.swing.JTextField();
        jtxtCliente = new javax.swing.JTextField();
        jtxtTele = new javax.swing.JTextField();
        jtxtFechaR = new javax.swing.JTextField();
        lblProdReci = new javax.swing.JLabel();
        lblFecha4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaInfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAreaFalla = new javax.swing.JTextArea();
        jtxtCedula = new javax.swing.JTextField();
        lblFecha6 = new javax.swing.JLabel();
        lblFecha3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        lblFecha5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblBarraTitulo = new javax.swing.JLabel();
        lblLineaInferior = new javax.swing.JLabel();
        lblLineaInferior1 = new javax.swing.JLabel();
        lblLineaInferior2 = new javax.swing.JLabel();
        lblLineaInferior3 = new javax.swing.JLabel();
        lblLineaInferior4 = new javax.swing.JLabel();
        lblLineaInferior5 = new javax.swing.JLabel();
        lblLineaInferior6 = new javax.swing.JLabel();
        lblLineaInferior7 = new javax.swing.JLabel();
        lblLineaInferior8 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn on_32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 5, 40, 40));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(java.awt.Color.white);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 460, 60));

        lblHora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHora.setForeground(java.awt.Color.white);
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Eliminar");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 505, 110, 30));

        lblFecha1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha1.setForeground(java.awt.Color.white);
        lblFecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha1.setText("Modificar");
        getContentPane().add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 120, 20));

        jtxtCatego.setBackground(new java.awt.Color(0, 0, 0));
        jtxtCatego.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtCatego.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCatego.setText("CATEGORIA");
        jtxtCatego.setBorder(null);
        jtxtCatego.setOpaque(false);
        jtxtCatego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCategoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCatego, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 239, 290, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 400, 40));

        lblHora2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHora2.setForeground(java.awt.Color.white);
        lblHora2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora2.setText("Buscar");
        getContentPane().add(lblHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 110, 30));

        jtxtImei.setBackground(new java.awt.Color(0, 0, 0));
        jtxtImei.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtImei.setForeground(new java.awt.Color(255, 255, 255));
        jtxtImei.setText("COD. IMEI");
        jtxtImei.setBorder(null);
        jtxtImei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtImeiActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, -1));

        jtxtMarca.setBackground(new java.awt.Color(0, 0, 0));
        jtxtMarca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtMarca.setForeground(new java.awt.Color(255, 255, 255));
        jtxtMarca.setText("MARCA");
        jtxtMarca.setBorder(null);
        jtxtMarca.setOpaque(false);
        jtxtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 264, 290, -1));

        jtxtModelo.setBackground(new java.awt.Color(0, 0, 0));
        jtxtModelo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtModelo.setForeground(new java.awt.Color(255, 255, 255));
        jtxtModelo.setText("MODELO");
        jtxtModelo.setBorder(null);
        jtxtModelo.setOpaque(false);
        jtxtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 290, -1));

        jtxtCompra.setBackground(new java.awt.Color(0, 0, 0));
        jtxtCompra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtCompra.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCompra.setText("R. COMPRA");
        jtxtCompra.setBorder(null);
        jtxtCompra.setOpaque(false);
        jtxtCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 315, 290, -1));

        jtxtCliente.setBackground(new java.awt.Color(0, 0, 0));
        jtxtCliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtCliente.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCliente.setText("CLIENTE");
        jtxtCliente.setBorder(null);
        jtxtCliente.setOpaque(false);
        jtxtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, -1));

        jtxtTele.setBackground(new java.awt.Color(0, 0, 0));
        jtxtTele.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtTele.setForeground(new java.awt.Color(255, 255, 255));
        jtxtTele.setText("TELEFONO");
        jtxtTele.setBorder(null);
        jtxtTele.setOpaque(false);
        jtxtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTeleActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 290, -1));

        jtxtFechaR.setBackground(new java.awt.Color(0, 0, 0));
        jtxtFechaR.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtFechaR.setForeground(new java.awt.Color(255, 255, 255));
        jtxtFechaR.setText("FECHA RECIBIDO");
        jtxtFechaR.setBorder(null);
        jtxtFechaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFechaRActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 205, 290, -1));

        lblProdReci.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProdReci.setForeground(java.awt.Color.white);
        lblProdReci.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProdReci.setText("Producto Recibido:");
        getContentPane().add(lblProdReci, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, 30));

        lblFecha4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblFecha4.setForeground(java.awt.Color.white);
        lblFecha4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha4.setText("Informacion del Tecnico");
        getContentPane().add(lblFecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 340, 20));

        jAreaInfo.setBackground(new java.awt.Color(204, 0, 0));
        jAreaInfo.setColumns(20);
        jAreaInfo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jAreaInfo.setForeground(new java.awt.Color(255, 255, 255));
        jAreaInfo.setRows(5);
        jAreaInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        jScrollPane1.setViewportView(jAreaInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 340, 90));

        jAreaFalla.setBackground(new java.awt.Color(204, 0, 0));
        jAreaFalla.setColumns(20);
        jAreaFalla.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jAreaFalla.setForeground(new java.awt.Color(255, 255, 255));
        jAreaFalla.setRows(5);
        jAreaFalla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAreaFalla.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(jAreaFalla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 340, 90));

        jtxtCedula.setBackground(new java.awt.Color(0, 0, 0));
        jtxtCedula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtxtCedula.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCedula.setText("CEDULA");
        jtxtCedula.setBorder(null);
        jtxtCedula.setOpaque(false);
        jtxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 365, 290, -1));

        lblFecha6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblFecha6.setForeground(java.awt.Color.white);
        lblFecha6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha6.setText("Descripcion de la falla:");
        getContentPane().add(lblFecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 300, 20));

        lblFecha3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha3.setForeground(java.awt.Color.white);
        lblFecha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha3.setText("Nuevo");
        getContentPane().add(lblFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, 20));

        jComboBox4.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setBorder(null);
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 210, 30));

        jComboBox5.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.setBorder(null);
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 210, 30));

        jComboBox6.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox6.setBorder(null);
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 210, 30));

        jComboBox3.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setBorder(null);
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 210, 30));

        lblFecha5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblFecha5.setForeground(java.awt.Color.white);
        lblFecha5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFecha5.setText("Fecha Conducta:");
        getContentPane().add(lblFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 180, 20));

        jTextField1.setBackground(new java.awt.Color(204, 0, 0));
        jTextField1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 210, 30));
        getContentPane().add(lblBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 500, 10));
        getContentPane().add(lblLineaInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 194, 310, 7));
        getContentPane().add(lblLineaInferior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 7));
        getContentPane().add(lblLineaInferior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, 310, 7));
        getContentPane().add(lblLineaInferior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 310, 7));
        getContentPane().add(lblLineaInferior4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 305, 310, 7));
        getContentPane().add(lblLineaInferior5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 310, 7));
        getContentPane().add(lblLineaInferior6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 310, 7));
        getContentPane().add(lblLineaInferior7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 310, 7));
        getContentPane().add(lblLineaInferior8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 405, 310, 7));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0){
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);
            
        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void jtxtCategoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCategoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCategoActionPerformed

    private void jtxtImeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtImeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtImeiActionPerformed

    private void jtxtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMarcaActionPerformed

    private void jtxtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtModeloActionPerformed

    private void jtxtCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCompraActionPerformed

    private void jtxtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtClienteActionPerformed

    private void jtxtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTeleActionPerformed

    private void jtxtFechaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFechaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFechaRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfGarantias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfGarantias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAreaFalla;
    private javax.swing.JTextArea jAreaInfo;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtxtCatego;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtCliente;
    private javax.swing.JTextField jtxtCompra;
    private javax.swing.JTextField jtxtFechaR;
    private javax.swing.JTextField jtxtImei;
    private javax.swing.JTextField jtxtMarca;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextField jtxtTele;
    private javax.swing.JLabel lblBarraTitulo;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha3;
    private javax.swing.JLabel lblFecha4;
    private javax.swing.JLabel lblFecha5;
    private javax.swing.JLabel lblFecha6;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora2;
    private javax.swing.JLabel lblLineaInferior;
    private javax.swing.JLabel lblLineaInferior1;
    private javax.swing.JLabel lblLineaInferior2;
    private javax.swing.JLabel lblLineaInferior3;
    private javax.swing.JLabel lblLineaInferior4;
    private javax.swing.JLabel lblLineaInferior5;
    private javax.swing.JLabel lblLineaInferior6;
    private javax.swing.JLabel lblLineaInferior7;
    private javax.swing.JLabel lblLineaInferior8;
    private javax.swing.JLabel lblProdReci;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
