/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import funciones_varias.Img_fondo_label;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwki
 */
public class jfMenu extends javax.swing.JFrame {

    /**
     * Creates new form jfMenu
     */
    public jfMenu() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //FONDO CON IMAGEN--------------------------------------------------------------------------------
        Img_fondo_label fondoLabel = new Img_fondo_label();
        fondoLabel.Llenar_Label("ventana_principal.jpg", lblFondo);
        fondoLabel.Llenar_Label("daika adm.png", lblNombreCliente);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalir = new javax.swing.JLabel();
        lblPersonas = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        lblTexto_reportes = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblTexto_personas = new javax.swing.JLabel();
        lblTexto_ventas = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn on_32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 5, 40, 40));

        lblPersonas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.png"))); // NOI18N
        lblPersonas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPersonasMouseMoved(evt);
            }
        });
        lblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPersonasMouseExited(evt);
            }
        });
        getContentPane().add(lblPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 230, 250));

        lblReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        lblReportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblReportesMouseMoved(evt);
            }
        });
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportesMouseExited(evt);
            }
        });
        getContentPane().add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 230, 250));

        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas.png"))); // NOI18N
        lblVentas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVentasMouseMoved(evt);
            }
        });
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVentasMouseExited(evt);
            }
        });
        getContentPane().add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 230, 260));

        lblTexto_reportes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTexto_reportes.setForeground(java.awt.Color.white);
        lblTexto_reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto_reportes.setText("Reportes");
        getContentPane().add(lblTexto_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 230, 40));

        lblNombreCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNombreCliente.setForeground(java.awt.Color.white);
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 240, 40));

        lblTexto_personas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTexto_personas.setForeground(java.awt.Color.white);
        lblTexto_personas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto_personas.setText("Personas");
        getContentPane().add(lblTexto_personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 230, -1));

        lblTexto_ventas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTexto_ventas.setForeground(java.awt.Color.white);
        lblTexto_ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto_ventas.setText("Ventas");
        getContentPane().add(lblTexto_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 190, 40));

        lblHora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHora.setForeground(java.awt.Color.white);
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 110, 30));

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha.setForeground(java.awt.Color.white);
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 100, 20));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0){
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            jfLogin login = new jfLogin();
            login.setVisible(true);            
        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblPersonasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonasMouseMoved
        lblPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblPersonasMouseMoved

    private void lblPersonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonasMouseExited
        lblPersonas.setBorder(null);
    }//GEN-LAST:event_lblPersonasMouseExited

    private void lblVentasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseMoved
        lblVentas.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblVentasMouseMoved

    private void lblVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseExited
        lblVentas.setBorder(null);
    }//GEN-LAST:event_lblVentasMouseExited

    private void lblReportesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseMoved
        lblReportes.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblReportesMouseMoved

    private void lblReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseExited
        lblReportes.setBorder(null);
    }//GEN-LAST:event_lblReportesMouseExited

    private void lblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonasMouseClicked
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
        jfPersonas persona = new jfPersonas();
        persona.setVisible(true);
    }//GEN-LAST:event_lblPersonasMouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
        jfVentas venta = new jfVentas();
        venta.setVisible(true);
    }//GEN-LAST:event_lblVentasMouseClicked

    private void lblReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseClicked
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
        jfReportes reporte = new jfReportes();
        reporte.setVisible(true);
    }//GEN-LAST:event_lblReportesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPersonas;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTexto_personas;
    private javax.swing.JLabel lblTexto_reportes;
    private javax.swing.JLabel lblTexto_ventas;
    private javax.swing.JLabel lblVentas;
    // End of variables declaration//GEN-END:variables
}
