/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import funciones_varias.Img_fondo_label;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author wwwki
 */
public class jfPagar extends javax.swing.JFrame {
    public static Integer id_factura;
        

    /**
     * Creates new form jfPagar_cuentas
     */
    public jfPagar() {
        initComponents();        
        this.setLocationRelativeTo(null);      
        
        Img_fondo_label fondoLabel = new Img_fondo_label();
        fondoLabel.Llenar_Label("barra_titulo.png", lblLineaInferio);
        fondoLabel.Llenar_Label("barra_titulo.png", lblLineaInferio1);
        
//        idex_combo combo = new idex_combo();
//        combo.llenarCombo(jcboTipoPago, "id_tipo_pago", "ttipo_pago", "txt_tipo_pago");
//        combo.llenarCombo(jcboSerieRecibo, "id_serie_recibo", "tserie_recibo", "txt_no_serie_recibo");
    }
                        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnGrabar = new javax.swing.JButton();
        jbtnBitacora = new javax.swing.JButton();
        jbtnDetalle = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblTotal = new javax.swing.JLabel();
        lblPendiente = new javax.swing.JLabel();
        jtxtAbono = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jtxtComprobante = new javax.swing.JTextField();
        jcboSerieRecibo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcboTipoPago = new javax.swing.JComboBox<>();
        lblLineaInferio = new javax.swing.JLabel();
        lblLineaInferio1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 380, 10));

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn on_32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 40));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Pagar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Recibo No. :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total a Pagar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Pendiente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 223, 230, 10));

        jbtnGrabar.setBackground(java.awt.Color.black);
        jbtnGrabar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jbtnGrabar.setForeground(new java.awt.Color(232, 251, 244));
        jbtnGrabar.setText("Grabar");
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 370, 30));

        jbtnBitacora.setBackground(java.awt.Color.black);
        jbtnBitacora.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jbtnBitacora.setForeground(new java.awt.Color(232, 251, 244));
        jbtnBitacora.setText("Bitacora");
        jbtnBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBitacoraActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 30));

        jbtnDetalle.setBackground(java.awt.Color.black);
        jbtnDetalle.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jbtnDetalle.setForeground(new java.awt.Color(232, 251, 244));
        jbtnDetalle.setText("Detalle Factura");
        jbtnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 130, 30));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 251, 244));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Serie:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 40, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 251, 244));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 251, 244));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("No. Factura:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 133, 230, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 182, 230, 10));

        lblTotal.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(232, 251, 244));
        lblTotal.setText("0.00");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, 20));

        lblPendiente.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        lblPendiente.setForeground(java.awt.Color.orange);
        lblPendiente.setText("0.00");
        jPanel1.add(lblPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, 20));

        jtxtAbono.setBackground(new java.awt.Color(0, 0, 0));
        jtxtAbono.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jtxtAbono.setForeground(java.awt.Color.green);
        jtxtAbono.setText("0.00");
        jtxtAbono.setBorder(null);
        jPanel1.add(jtxtAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, 20));

        lblFecha.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(232, 251, 244));
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 90, 20));

        lblSerie.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblSerie.setForeground(new java.awt.Color(232, 251, 244));
        jPanel1.add(lblSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 68, 70, 20));

        lblNo.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblNo.setForeground(new java.awt.Color(232, 251, 244));
        jPanel1.add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, 20));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Abonar:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo de Pago:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 230, 10));

        jtxtComprobante.setBackground(new java.awt.Color(41, 42, 44));
        jtxtComprobante.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jtxtComprobante.setForeground(java.awt.Color.green);
        jtxtComprobante.setBorder(null);
        jPanel1.add(jtxtComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 230, 20));

        jcboSerieRecibo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jcboSerieRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboSerieReciboActionPerformed(evt);
            }
        });
        jPanel1.add(jcboSerieRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 230, -1));

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("No. Serie:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, -1));

        jcboTipoPago.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jPanel1.add(jcboTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 230, -1));
        jPanel1.add(lblLineaInferio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 7));
        jPanel1.add(lblLineaInferio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, 7));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0){
            //Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, this);
            //Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            jfFinanzas mp = new jfFinanzas();
            this.dispose();
            mp.setVisible(true);
            Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, mp);

        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void jbtnBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBitacoraActionPerformed
        
        jfBitacora_finanza bp = new jfBitacora_finanza();
//        bp.idFactura = id_factura;
//        bp.mostrar_bitacora();
//        bp.lblSerie.setText(lblSerie.getText());
//        bp.lblNo.setText(lblNo.getText());
//        bp.lblFecha.setText(lblFecha.getText());
        bp.setVisible(true);
    }//GEN-LAST:event_jbtnBitacoraActionPerformed

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed
        
    }//GEN-LAST:event_jbtnGrabarActionPerformed

    private void jbtnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetalleActionPerformed
        jfDetalle_f bp = new jfDetalle_f();
//        bp.idFactura = id_factura;
//        bp.mostrar_detalle();
//        bp.lblSerie.setText(lblSerie.getText());
//        bp.lblNo.setText(lblNo.getText());
//        bp.lblFecha.setText(lblFecha.getText());
        bp.setVisible(true);
    }//GEN-LAST:event_jbtnDetalleActionPerformed

    private void jcboSerieReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboSerieReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboSerieReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPagar().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton jbtnBitacora;
    private javax.swing.JButton jbtnDetalle;
    private javax.swing.JButton jbtnGrabar;
    private javax.swing.JComboBox<String> jcboSerieRecibo;
    private javax.swing.JComboBox<String> jcboTipoPago;
    private javax.swing.JTextField jtxtAbono;
    private javax.swing.JTextField jtxtComprobante;
    public static javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLineaInferio;
    private javax.swing.JLabel lblLineaInferio1;
    public static javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblPendiente;
    private javax.swing.JLabel lblSalir;
    public static javax.swing.JLabel lblSerie;
    public static javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
