/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import funciones_varias.Img_fondo_label;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwki
 */
public class jfPersonas extends javax.swing.JFrame {

    /**
     * Creates new form jfMenu
     */
    public jfPersonas() {
        initComponents();
        
        this.setLocationRelativeTo(null);                      
        //FONDO CON IMAGEN--------------------------------------------------------------------------------
        Img_fondo_label fondoLabel = new Img_fondo_label();
        fondoLabel.Llenar_Label("ventana_principal.jpg", lblFondo);
        fondoLabel.Llenar_Label("daika adm.png", lblNombreCliente);                
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalir = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblEmpleados = new javax.swing.JLabel();
        lblTexto_clientes = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblTextp_usuario = new javax.swing.JLabel();
        lblTexto_empleados = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn on_32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 5, 40, 40));

        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        lblUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseMoved(evt);
            }
        });
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, 250));

        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N
        lblClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblClientesMouseMoved(evt);
            }
        });
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClientesMouseExited(evt);
            }
        });
        getContentPane().add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 230, 270));

        lblEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados.png"))); // NOI18N
        lblEmpleados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblEmpleadosMouseMoved(evt);
            }
        });
        lblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmpleadosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmpleadosMouseExited(evt);
            }
        });
        getContentPane().add(lblEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 300, 270));

        lblTexto_clientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTexto_clientes.setForeground(java.awt.Color.white);
        lblTexto_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto_clientes.setText("Clientes");
        lblTexto_clientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTexto_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 230, 70));

        lblNombreCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNombreCliente.setForeground(java.awt.Color.white);
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 250, 50));

        lblTextp_usuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTextp_usuario.setForeground(java.awt.Color.white);
        lblTextp_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextp_usuario.setText("Usuarios");
        lblTextp_usuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTextp_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 70));

        lblTexto_empleados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTexto_empleados.setForeground(java.awt.Color.white);
        lblTexto_empleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto_empleados.setText("Empleados");
        getContentPane().add(lblTexto_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 230, -1));

        lblHora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHora.setForeground(java.awt.Color.white);
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 110, 30));

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha.setForeground(java.awt.Color.white);
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 100, 20));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
        jfMenu menu = new jfMenu();
        menu.setVisible(true);
        
        
//        int dialog = JOptionPane.YES_NO_OPTION;
//        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
//        if(result == 0){
//            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);
//            
//        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseMoved
        lblUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblUsuariosMouseMoved

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited
        lblUsuarios.setBorder(null);
    }//GEN-LAST:event_lblUsuariosMouseExited

    private void lblEmpleadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadosMouseMoved
        lblEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblEmpleadosMouseMoved

    private void lblEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadosMouseExited
        lblEmpleados.setBorder(null);
    }//GEN-LAST:event_lblEmpleadosMouseExited

    private void lblClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseMoved
        lblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblClientesMouseMoved

    private void lblClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseExited
        lblClientes.setBorder(null);
    }//GEN-LAST:event_lblClientesMouseExited

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE); 
        jfUsuarios usu = new jfUsuarios();
        usu.setVisible(true);
    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadosMouseClicked
        
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE); 
        jfEmpleados emple = new jfEmpleados();
        emple.setVisible(true);        
    }//GEN-LAST:event_lblEmpleadosMouseClicked

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
       Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE); 
       jfClientes cli = new jfClientes();
       cli.setVisible(true);
    }//GEN-LAST:event_lblClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTexto_clientes;
    private javax.swing.JLabel lblTexto_empleados;
    private javax.swing.JLabel lblTextp_usuario;
    private javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables
}
