/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwki
 */
public class jfProductos extends javax.swing.JFrame {

    /**
     * Creates new form jfMenu
     */
    public jfProductos() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //FONDO CON IMAGEN--------------------------------------------------------------------------------
        ImageIcon imagen = new ImageIcon("src\\Imagenes\\productos.jpeg");        
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);
        lblFondo.repaint();
        
        
        jtxtImei.setBackground(new Color(0,0,0,64));
        jtxtCompra.setBackground(new Color(0,0,0,64));
        jtxtCosto.setBackground(new Color(0,0,0,64));
        
        jtxtTasa.setBackground(new Color(0,0,0,64));
        jtxtGanancia.setBackground(new Color(0,0,0,64));
        
        //jsepImei.setBackground(Color.red);
        sep1.setForeground(Color.green); // top line color
        sep1.setBackground(Color.green.brighter()); // bottom line color
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalir = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblHora1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtCompra = new javax.swing.JTextField();
        jtxtCosto = new javax.swing.JTextField();
        jtxtImei = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        sep3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jtxtTasa = new javax.swing.JTextField();
        sep4 = new javax.swing.JSeparator();
        jtxtGanancia = new javax.swing.JTextField();
        sep5 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn on_32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        getContentPane().add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 5, 40, 40));

        lblNombreCliente.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNombreCliente.setForeground(java.awt.Color.white);
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setText("Productos");
        getContentPane().add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, -1));

        lblHora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHora.setForeground(java.awt.Color.white);
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Eliminar");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 110, 30));

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha.setForeground(java.awt.Color.white);
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Nuevo");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, 20));

        lblFecha1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha1.setForeground(java.awt.Color.white);
        lblFecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha1.setText("Modificar");
        getContentPane().add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 120, 20));

        lblHora1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHora1.setForeground(java.awt.Color.white);
        lblHora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora1.setText("Buscar");
        getContentPane().add(lblHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 110, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROOVEDOR", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 20));

        jComboBox2.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(null);
        jComboBox2.setOpaque(false);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 162, 270, 20));

        jComboBox3.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARCA", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setBorder(null);
        jComboBox3.setOpaque(false);
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 184, 270, 20));

        jComboBox4.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODELO", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setBorder(null);
        jComboBox4.setOpaque(false);
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 207, 270, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 131, 680, 260));

        jtxtCompra.setBackground(new java.awt.Color(0, 0, 0));
        jtxtCompra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtxtCompra.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCompra.setText("R. COMPRA *");
        jtxtCompra.setBorder(null);
        getContentPane().add(jtxtCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 260, 265, -1));

        jtxtCosto.setBackground(new java.awt.Color(0, 0, 0));
        jtxtCosto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtxtCosto.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCosto.setText("COSTO *");
        jtxtCosto.setBorder(null);
        getContentPane().add(jtxtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 290, 265, -1));

        jtxtImei.setBackground(new java.awt.Color(0, 0, 0));
        jtxtImei.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtxtImei.setForeground(new java.awt.Color(255, 255, 255));
        jtxtImei.setText("COD. IMEI *");
        jtxtImei.setBorder(null);
        jtxtImei.setOpaque(false);
        getContentPane().add(jtxtImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 230, 265, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, -1));
        getContentPane().add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 270, 10));
        getContentPane().add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, 10));
        getContentPane().add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, 10));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 270, 30));

        jtxtTasa.setBackground(new java.awt.Color(0, 0, 0));
        jtxtTasa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtxtTasa.setForeground(new java.awt.Color(255, 255, 255));
        jtxtTasa.setText("Tasa del día");
        jtxtTasa.setBorder(null);
        jtxtTasa.setOpaque(false);
        getContentPane().add(jtxtTasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 200, -1));
        getContentPane().add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 200, 10));

        jtxtGanancia.setBackground(new java.awt.Color(0, 0, 0));
        jtxtGanancia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtxtGanancia.setForeground(new java.awt.Color(255, 255, 255));
        jtxtGanancia.setText("% de Ganancia");
        jtxtGanancia.setBorder(null);
        jtxtGanancia.setOpaque(false);
        getContentPane().add(jtxtGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 200, -1));
        getContentPane().add(sep5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 200, 10));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0){
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);
            
        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtCompra;
    private javax.swing.JTextField jtxtCosto;
    private javax.swing.JTextField jtxtGanancia;
    private javax.swing.JTextField jtxtImei;
    private javax.swing.JTextField jtxtTasa;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JSeparator sep5;
    // End of variables declaration//GEN-END:variables
}
